### ISSUE TITLE
Can I use desktop_capture module ?

### ISSUE THREAD

**Issue by EbramTawfik** [Microsoft/WebRTC-universal-samples#18] opened 2018-05-08 18:48 UTC
Hi @jamescadd @robin-raymond ,
Is there a way to use desktop_capture module for capturing the screen and stream it instead of sharing camera and file ?

If there is .. Is there a code sample for sharing screen ?

The implementation for screen capture already there for windows :
https://chromium.googlesource.com/external/webrtc.git/+/3e4faae0edeb2b30e899712f92217d2aa5cd6ff2/webrtc/modules/desktop_capture/

and Here is a code sample use the desktop_capture module for sharing desktop and it works for WPF and Windows 7 :
https://github.com/radioman/WebRtc.NET/tree/staging
   
Thanks,
Ebram

**Comment by jamescadd** [comment] 2018-06-23 15:14
Duplicate of https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/47

**Closed by jamescadd** 2018-06-23 15:14 UTC
